import json
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def render_scada_dashboard(network_json_path, solved_p1, steady_flow):
    """
    Renders the vertically stacked UI: 
    Topology Map -> Pressure Gradient -> SCADA Table.
    """
    # 1. Load the data structure
    with open(network_json_path, "r") as file:
        data = json.loads(file.read())
    
    nodes = data["nodes"]
    
    # Extract structural data
    x_cord = [n["x_cord"] for n in nodes]
    node_ids = [n["id"] for n in nodes]
    node_types = [n["type"].upper() for n in nodes]
    
    # Map the solved Newton-Raphson pressure back into the dataset
    pressures = [
        nodes[0]["boundary_pressure_bar"], 
        solved_p1, 
        nodes[2]["boundary_pressure_bar"]
    ]
    
    # Define a default system status
    statuses = ["🟢 NOMINAL", "🟢 NOMINAL", "🟢 NOMINAL"]

    # 2. Initialize the 3-Tier Vertically Stacked Layout
    # We allocate 30% height to the map, 40% to the chart, and 30% to the table
    fig = make_subplots(
        rows=3, cols=1, 
        shared_xaxes=False,
        row_heights=[0.3, 0.4, 0.3],
        vertical_spacing=0.1,
        specs=[
            [{"type": "scatter"}],
            [{"type": "scatter"}],
            [{"type": "table"}]
        ],
        subplot_titles=(
            'Network Topology Map (Pipe thickness reflects flow rate)', 
            'Pressure Gradient Chart (bar)', 
            'Live SCADA Telemetry Matrix'
        )
    )

    # 3. TIER 1: Network Topology Map
    dynamic_line_width = max(2, steady_flow * 150) 
    fig.add_trace(go.Scatter(
        x=x_cord, 
        y=[0, 0, 0],  # Plotted on a flat 2D elevation plane
        mode='lines+markers+text',
        marker=dict(size=22, color='#1f77b4', line=dict(width=2, color='DarkSlateGrey')),
        line=dict(width=dynamic_line_width, color='#aec7e8'),
        text=node_ids,
        textposition="top center",
        hoverinfo='text',
        hovertext=[f"{nid}<br>Flow: {steady_flow:.4f} kg/s" for nid in node_ids]
    ), row=1, col=1)

    # 4. TIER 2: Pressure Gradient Chart
    fig.add_trace(go.Scatter(
        x=x_cord, 
        y=pressures, 
        mode='lines+markers',
        marker=dict(size=14, color='#d62728', symbol='diamond'),
        line=dict(width=4, color='#ff9896', dash='solid'),
        hoverinfo='y',
        hovertext=[f"Pressure: {p:.2f} bar" for p in pressures]
    ), row=2, col=1)

    # 5. TIER 3: The Live SCADA Table
    fig.add_trace(go.Table(
        header=dict(
            values=["<b>Node ID</b>", "<b>Node Type</b>", "<b>Position X (m)</b>", "<b>Pressure (bar)</b>", "<b>System Status</b>"],
            fill_color='#2c3e50',
            font=dict(color='white', size=14),
            align='left'
        ),
        cells=dict(
            values=[node_ids, node_types, x_cord, [f"{p:.2f}" for p in pressures], statuses],
            fill_color='#ecf0f1',
            font=dict(color='#2c3e50', size=13),
            align='left',
            height=30
        )
    ), row=3, col=1)

    # 6. UI/UX Formatting
    fig.update_layout(
        height=850, 
        showlegend=False, 
        title_text="Pipeline Micro-Grid: Live SCADA Digital Twin",
        title_font_size=24,
        plot_bgcolor='rgba(250, 250, 250, 1)',
        paper_bgcolor='rgba(255, 255, 255, 1)'
    )
    
    # Clean up axes
    fig.update_yaxes(title_text="", row=1, col=1, showticklabels=False, range=[-1, 1])
    fig.update_xaxes(title_text="Physical Distance (meters)", row=1, col=1)
    
    fig.update_yaxes(title_text="Pressure (bar)", row=2, col=1, range=[0, 110])
    fig.update_xaxes(title_text="Physical Distance (meters)", row=2, col=1)

    # Render interactive HTML
    fig.show()

if __name__ == "__main__":
    # Passing in the exact output generated by your steady_state_solver.py
    SOLVED_PRESSURE = 75.000033
    STEADY_FLOW = 0.055536
    
    print("Generating Complete Vertically Stacked Plotly Dashboard...")
    render_scada_dashboard("network_config.json", SOLVED_PRESSURE, STEADY_FLOW)